[tool.poetry]
name = "onesub"
version = "0.1.0"
description = "An AI-based subscription management center"
authors = ["tztsai <lord@feedup.today>"]
license = "MIT"
readme = "README.md"
homepage = "https://yourprojecthomepage.com"
repository = "https://github.com/yourusername/onesub"
documentation = "https://yourprojectdocs.com"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^2.1.1"
google-auth = "^2.6.0"
google-auth-oauthlib = "^0.5.0"
google-api-python-client = "^2.31.0"
requests = "^2.26.0"
Jinja2 = "^3.0.3"
Django = "^3.2"
djangorestframework = "^3.12.4"
openai = "^0.10.2"
boto3 = "^1.35.54"
django-ses = "^4.2.0"

[tool.poetry.dev-dependencies]
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
start = "onesub.app:main"