package app.atmaware.ruminer.core.datastore

// Keys
const val ruminerSelfHostedApiServer =  "ruminerSelfHostedAPIServer"
const val ruminerSelfHostedWebServer = "ruminerSelfHostedWebServer"
const val ruminerAuthToken =  "ruminerAuthToken"
const val ruminerAuthCookieString =  "ruminerAuthCookieString"
const val ruminerPendingUserToken =  "ruminerPendingUserToken"
const val libraryLastSyncTimestamp = "libraryLastSyncTimestamp"
const val preferredWebFontSize = "preferredWebFontSize"
const val preferredWebLineHeight = "preferredWebLineHeight"
const val preferredWebMaxWidthPercentage = "preferredWebMaxWidthPercentage"
const val preferredWebFontFamily = "preferredWebFontFamily"
const val prefersWebHighContrastText = "prefersWebHighContrastText"
const val prefersJustifyText = "prefersJustifyText"
const val lastUsedSavedItemFilter = "lastUsedSavedItemFilter"
const val lastUsedSavedItemSortFilter = "lastUsedSavedItemSortFilter"
const val preferredTheme = "preferredTheme"
const val followingTabActive = "followingTabActive"
const val volumeForScroll = "volumeForScroll"
const val rtlText = "rtlText"
